#!/bin/bash
## SLURM scrips have a specific format.

## job name
#SBATCH --job-name=grid_1_
#SBATCH --gres=gpu:1
#SBATCH --time=20:00:00

## %j is the job id, %u is the user id
## coment SBATCH --output=/u/kentonza/Code/snr_optimizer/pytorch/cifar10/%u/jobs/grid_1-%j.out
## filename for job standard error output (stderr)
## coment SBATCH --error=/u/kentonza/Code/snr_optimizer/pytorch/cifar10/%u/jobs/grid_1-%j.err

## number of nodes
#SBATCH --nodes=1
## number of tasks per node
#SBATCH --ntasks-per-node=1


### Section 2: Setting environment variables for the job
#FIXME
source activate py2

### Section 3:
### Jobs command
### Generated by gen.sh
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed1lr1e-3 -ps  -a 1 --seed 1 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed1lr5e-3 -ps  -a 1 --seed 1 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed1lr1e-2 -ps  -a 1 --seed 1 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed1lr5e-2 -ps  -a 1 --seed 1 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed2lr1e-3 -ps  -a 1 --seed 2 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed2lr5e-3 -ps  -a 1 --seed 2 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed2lr1e-2 -ps  -a 1 --seed 2 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed2lr5e-2 -ps  -a 1 --seed 2 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed3lr1e-3 -ps  -a 1 --seed 3 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed3lr5e-3 -ps  -a 1 --seed 3 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed3lr1e-2 -ps  -a 1 --seed 3 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed3lr5e-2 -ps  -a 1 --seed 3 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed4lr1e-3 -ps  -a 1 --seed 4 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed4lr5e-3 -ps  -a 1 --seed 4 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed4lr1e-2 -ps  -a 1 --seed 4 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed4lr5e-2 -ps  -a 1 --seed 4 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed5lr1e-3 -ps  -a 1 --seed 5 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed5lr5e-3 -ps  -a 1 --seed 5 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed5lr1e-2 -ps  -a 1 --seed 5 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed5lr5e-2 -ps  -a 1 --seed 5 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed6lr1e-3 -ps  -a 1 --seed 6 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed6lr5e-3 -ps  -a 1 --seed 6 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed6lr1e-2 -ps  -a 1 --seed 6 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed6lr5e-2 -ps  -a 1 --seed 6 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed7lr1e-3 -ps  -a 1 --seed 7 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed7lr5e-3 -ps  -a 1 --seed 7 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed7lr1e-2 -ps  -a 1 --seed 7 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed7lr5e-2 -ps  -a 1 --seed 7 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed8lr1e-3 -ps  -a 1 --seed 8 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed8lr5e-3 -ps  -a 1 --seed 8 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed8lr1e-2 -ps  -a 1 --seed 8 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed8lr5e-2 -ps  -a 1 --seed 8 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed9lr1e-3 -ps  -a 1 --seed 9 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed9lr5e-3 -ps  -a 1 --seed 9 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed9lr1e-2 -ps  -a 1 --seed 9 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed9lr5e-2 -ps  -a 1 --seed 9 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed10lr1e-3 -ps  -a 1 --seed 10 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed10lr5e-3 -ps  -a 1 --seed 10 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed10lr1e-2 -ps  -a 1 --seed 10 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/psa1seed10lr5e-2 -ps  -a 1 --seed 10 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed1lr1e-3 -ps 0.5 -a 10 --seed 1 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed1lr5e-3 -ps 0.5 -a 10 --seed 1 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed1lr1e-2 -ps 0.5 -a 10 --seed 1 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed1lr5e-2 -ps 0.5 -a 10 --seed 1 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed1lr1e-3 -ps 0.5 -a 20 --seed 1 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed1lr5e-3 -ps 0.5 -a 20 --seed 1 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed1lr1e-2 -ps 0.5 -a 20 --seed 1 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed1lr5e-2 -ps 0.5 -a 20 --seed 1 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed1lr1e-3 -ps 0.5 -a 30 --seed 1 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed1lr5e-3 -ps 0.5 -a 30 --seed 1 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed1lr1e-2 -ps 0.5 -a 30 --seed 1 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed1lr5e-2 -ps 0.5 -a 30 --seed 1 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed1lr1e-3 -ps 0.75 -a 10 --seed 1 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed1lr5e-3 -ps 0.75 -a 10 --seed 1 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed1lr1e-2 -ps 0.75 -a 10 --seed 1 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed1lr5e-2 -ps 0.75 -a 10 --seed 1 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed1lr1e-3 -ps 0.75 -a 20 --seed 1 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed1lr5e-3 -ps 0.75 -a 20 --seed 1 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed1lr1e-2 -ps 0.75 -a 20 --seed 1 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed1lr5e-2 -ps 0.75 -a 20 --seed 1 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed1lr1e-3 -ps 0.75 -a 30 --seed 1 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed1lr5e-3 -ps 0.75 -a 30 --seed 1 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed1lr1e-2 -ps 0.75 -a 30 --seed 1 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed1lr5e-2 -ps 0.75 -a 30 --seed 1 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed2lr1e-3 -ps 0.5 -a 10 --seed 2 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed2lr5e-3 -ps 0.5 -a 10 --seed 2 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed2lr1e-2 -ps 0.5 -a 10 --seed 2 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed2lr5e-2 -ps 0.5 -a 10 --seed 2 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed2lr1e-3 -ps 0.5 -a 20 --seed 2 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed2lr5e-3 -ps 0.5 -a 20 --seed 2 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed2lr1e-2 -ps 0.5 -a 20 --seed 2 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed2lr5e-2 -ps 0.5 -a 20 --seed 2 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed2lr1e-3 -ps 0.5 -a 30 --seed 2 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed2lr5e-3 -ps 0.5 -a 30 --seed 2 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed2lr1e-2 -ps 0.5 -a 30 --seed 2 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed2lr5e-2 -ps 0.5 -a 30 --seed 2 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed2lr1e-3 -ps 0.75 -a 10 --seed 2 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed2lr5e-3 -ps 0.75 -a 10 --seed 2 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed2lr1e-2 -ps 0.75 -a 10 --seed 2 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed2lr5e-2 -ps 0.75 -a 10 --seed 2 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed2lr1e-3 -ps 0.75 -a 20 --seed 2 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed2lr5e-3 -ps 0.75 -a 20 --seed 2 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed2lr1e-2 -ps 0.75 -a 20 --seed 2 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed2lr5e-2 -ps 0.75 -a 20 --seed 2 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed2lr1e-3 -ps 0.75 -a 30 --seed 2 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed2lr5e-3 -ps 0.75 -a 30 --seed 2 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed2lr1e-2 -ps 0.75 -a 30 --seed 2 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed2lr5e-2 -ps 0.75 -a 30 --seed 2 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed3lr1e-3 -ps 0.5 -a 10 --seed 3 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed3lr5e-3 -ps 0.5 -a 10 --seed 3 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed3lr1e-2 -ps 0.5 -a 10 --seed 3 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed3lr5e-2 -ps 0.5 -a 10 --seed 3 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed3lr1e-3 -ps 0.5 -a 20 --seed 3 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed3lr5e-3 -ps 0.5 -a 20 --seed 3 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed3lr1e-2 -ps 0.5 -a 20 --seed 3 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed3lr5e-2 -ps 0.5 -a 20 --seed 3 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed3lr1e-3 -ps 0.5 -a 30 --seed 3 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed3lr5e-3 -ps 0.5 -a 30 --seed 3 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed3lr1e-2 -ps 0.5 -a 30 --seed 3 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed3lr5e-2 -ps 0.5 -a 30 --seed 3 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed3lr1e-3 -ps 0.75 -a 10 --seed 3 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed3lr5e-3 -ps 0.75 -a 10 --seed 3 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed3lr1e-2 -ps 0.75 -a 10 --seed 3 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed3lr5e-2 -ps 0.75 -a 10 --seed 3 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed3lr1e-3 -ps 0.75 -a 20 --seed 3 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed3lr5e-3 -ps 0.75 -a 20 --seed 3 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed3lr1e-2 -ps 0.75 -a 20 --seed 3 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed3lr5e-2 -ps 0.75 -a 20 --seed 3 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed3lr1e-3 -ps 0.75 -a 30 --seed 3 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed3lr5e-3 -ps 0.75 -a 30 --seed 3 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed3lr1e-2 -ps 0.75 -a 30 --seed 3 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed3lr5e-2 -ps 0.75 -a 30 --seed 3 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed4lr1e-3 -ps 0.5 -a 10 --seed 4 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed4lr5e-3 -ps 0.5 -a 10 --seed 4 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed4lr1e-2 -ps 0.5 -a 10 --seed 4 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed4lr5e-2 -ps 0.5 -a 10 --seed 4 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed4lr1e-3 -ps 0.5 -a 20 --seed 4 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed4lr5e-3 -ps 0.5 -a 20 --seed 4 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed4lr1e-2 -ps 0.5 -a 20 --seed 4 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed4lr5e-2 -ps 0.5 -a 20 --seed 4 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed4lr1e-3 -ps 0.5 -a 30 --seed 4 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed4lr5e-3 -ps 0.5 -a 30 --seed 4 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed4lr1e-2 -ps 0.5 -a 30 --seed 4 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed4lr5e-2 -ps 0.5 -a 30 --seed 4 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed4lr1e-3 -ps 0.75 -a 10 --seed 4 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed4lr5e-3 -ps 0.75 -a 10 --seed 4 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed4lr1e-2 -ps 0.75 -a 10 --seed 4 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed4lr5e-2 -ps 0.75 -a 10 --seed 4 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed4lr1e-3 -ps 0.75 -a 20 --seed 4 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed4lr5e-3 -ps 0.75 -a 20 --seed 4 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed4lr1e-2 -ps 0.75 -a 20 --seed 4 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed4lr5e-2 -ps 0.75 -a 20 --seed 4 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed4lr1e-3 -ps 0.75 -a 30 --seed 4 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed4lr5e-3 -ps 0.75 -a 30 --seed 4 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed4lr1e-2 -ps 0.75 -a 30 --seed 4 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed4lr5e-2 -ps 0.75 -a 30 --seed 4 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed5lr1e-3 -ps 0.5 -a 10 --seed 5 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed5lr5e-3 -ps 0.5 -a 10 --seed 5 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed5lr1e-2 -ps 0.5 -a 10 --seed 5 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed5lr5e-2 -ps 0.5 -a 10 --seed 5 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed5lr1e-3 -ps 0.5 -a 20 --seed 5 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed5lr5e-3 -ps 0.5 -a 20 --seed 5 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed5lr1e-2 -ps 0.5 -a 20 --seed 5 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed5lr5e-2 -ps 0.5 -a 20 --seed 5 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed5lr1e-3 -ps 0.5 -a 30 --seed 5 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed5lr5e-3 -ps 0.5 -a 30 --seed 5 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed5lr1e-2 -ps 0.5 -a 30 --seed 5 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed5lr5e-2 -ps 0.5 -a 30 --seed 5 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed5lr1e-3 -ps 0.75 -a 10 --seed 5 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed5lr5e-3 -ps 0.75 -a 10 --seed 5 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed5lr1e-2 -ps 0.75 -a 10 --seed 5 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed5lr5e-2 -ps 0.75 -a 10 --seed 5 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed5lr1e-3 -ps 0.75 -a 20 --seed 5 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed5lr5e-3 -ps 0.75 -a 20 --seed 5 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed5lr1e-2 -ps 0.75 -a 20 --seed 5 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed5lr5e-2 -ps 0.75 -a 20 --seed 5 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed5lr1e-3 -ps 0.75 -a 30 --seed 5 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed5lr5e-3 -ps 0.75 -a 30 --seed 5 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed5lr1e-2 -ps 0.75 -a 30 --seed 5 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed5lr5e-2 -ps 0.75 -a 30 --seed 5 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed6lr1e-3 -ps 0.5 -a 10 --seed 6 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed6lr5e-3 -ps 0.5 -a 10 --seed 6 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed6lr1e-2 -ps 0.5 -a 10 --seed 6 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed6lr5e-2 -ps 0.5 -a 10 --seed 6 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed6lr1e-3 -ps 0.5 -a 20 --seed 6 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed6lr5e-3 -ps 0.5 -a 20 --seed 6 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed6lr1e-2 -ps 0.5 -a 20 --seed 6 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed6lr5e-2 -ps 0.5 -a 20 --seed 6 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed6lr1e-3 -ps 0.5 -a 30 --seed 6 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed6lr5e-3 -ps 0.5 -a 30 --seed 6 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed6lr1e-2 -ps 0.5 -a 30 --seed 6 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed6lr5e-2 -ps 0.5 -a 30 --seed 6 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed6lr1e-3 -ps 0.75 -a 10 --seed 6 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed6lr5e-3 -ps 0.75 -a 10 --seed 6 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed6lr1e-2 -ps 0.75 -a 10 --seed 6 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed6lr5e-2 -ps 0.75 -a 10 --seed 6 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed6lr1e-3 -ps 0.75 -a 20 --seed 6 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed6lr5e-3 -ps 0.75 -a 20 --seed 6 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed6lr1e-2 -ps 0.75 -a 20 --seed 6 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed6lr5e-2 -ps 0.75 -a 20 --seed 6 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed6lr1e-3 -ps 0.75 -a 30 --seed 6 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed6lr5e-3 -ps 0.75 -a 30 --seed 6 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed6lr1e-2 -ps 0.75 -a 30 --seed 6 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed6lr5e-2 -ps 0.75 -a 30 --seed 6 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed7lr1e-3 -ps 0.5 -a 10 --seed 7 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed7lr5e-3 -ps 0.5 -a 10 --seed 7 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed7lr1e-2 -ps 0.5 -a 10 --seed 7 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed7lr5e-2 -ps 0.5 -a 10 --seed 7 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed7lr1e-3 -ps 0.5 -a 20 --seed 7 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed7lr5e-3 -ps 0.5 -a 20 --seed 7 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed7lr1e-2 -ps 0.5 -a 20 --seed 7 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed7lr5e-2 -ps 0.5 -a 20 --seed 7 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed7lr1e-3 -ps 0.5 -a 30 --seed 7 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed7lr5e-3 -ps 0.5 -a 30 --seed 7 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed7lr1e-2 -ps 0.5 -a 30 --seed 7 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed7lr5e-2 -ps 0.5 -a 30 --seed 7 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed7lr1e-3 -ps 0.75 -a 10 --seed 7 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed7lr5e-3 -ps 0.75 -a 10 --seed 7 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed7lr1e-2 -ps 0.75 -a 10 --seed 7 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed7lr5e-2 -ps 0.75 -a 10 --seed 7 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed7lr1e-3 -ps 0.75 -a 20 --seed 7 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed7lr5e-3 -ps 0.75 -a 20 --seed 7 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed7lr1e-2 -ps 0.75 -a 20 --seed 7 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed7lr5e-2 -ps 0.75 -a 20 --seed 7 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed7lr1e-3 -ps 0.75 -a 30 --seed 7 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed7lr5e-3 -ps 0.75 -a 30 --seed 7 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed7lr1e-2 -ps 0.75 -a 30 --seed 7 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed7lr5e-2 -ps 0.75 -a 30 --seed 7 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed8lr1e-3 -ps 0.5 -a 10 --seed 8 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed8lr5e-3 -ps 0.5 -a 10 --seed 8 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed8lr1e-2 -ps 0.5 -a 10 --seed 8 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed8lr5e-2 -ps 0.5 -a 10 --seed 8 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed8lr1e-3 -ps 0.5 -a 20 --seed 8 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed8lr5e-3 -ps 0.5 -a 20 --seed 8 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed8lr1e-2 -ps 0.5 -a 20 --seed 8 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed8lr5e-2 -ps 0.5 -a 20 --seed 8 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed8lr1e-3 -ps 0.5 -a 30 --seed 8 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed8lr5e-3 -ps 0.5 -a 30 --seed 8 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed8lr1e-2 -ps 0.5 -a 30 --seed 8 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed8lr5e-2 -ps 0.5 -a 30 --seed 8 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed8lr1e-3 -ps 0.75 -a 10 --seed 8 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed8lr5e-3 -ps 0.75 -a 10 --seed 8 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed8lr1e-2 -ps 0.75 -a 10 --seed 8 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed8lr5e-2 -ps 0.75 -a 10 --seed 8 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed8lr1e-3 -ps 0.75 -a 20 --seed 8 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed8lr5e-3 -ps 0.75 -a 20 --seed 8 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed8lr1e-2 -ps 0.75 -a 20 --seed 8 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed8lr5e-2 -ps 0.75 -a 20 --seed 8 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed8lr1e-3 -ps 0.75 -a 30 --seed 8 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed8lr5e-3 -ps 0.75 -a 30 --seed 8 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed8lr1e-2 -ps 0.75 -a 30 --seed 8 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed8lr5e-2 -ps 0.75 -a 30 --seed 8 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed9lr1e-3 -ps 0.5 -a 10 --seed 9 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed9lr5e-3 -ps 0.5 -a 10 --seed 9 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed9lr1e-2 -ps 0.5 -a 10 --seed 9 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed9lr5e-2 -ps 0.5 -a 10 --seed 9 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed9lr1e-3 -ps 0.5 -a 20 --seed 9 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed9lr5e-3 -ps 0.5 -a 20 --seed 9 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed9lr1e-2 -ps 0.5 -a 20 --seed 9 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed9lr5e-2 -ps 0.5 -a 20 --seed 9 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed9lr1e-3 -ps 0.5 -a 30 --seed 9 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed9lr5e-3 -ps 0.5 -a 30 --seed 9 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed9lr1e-2 -ps 0.5 -a 30 --seed 9 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed9lr5e-2 -ps 0.5 -a 30 --seed 9 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed9lr1e-3 -ps 0.75 -a 10 --seed 9 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed9lr5e-3 -ps 0.75 -a 10 --seed 9 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed9lr1e-2 -ps 0.75 -a 10 --seed 9 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed9lr5e-2 -ps 0.75 -a 10 --seed 9 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed9lr1e-3 -ps 0.75 -a 20 --seed 9 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed9lr5e-3 -ps 0.75 -a 20 --seed 9 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed9lr1e-2 -ps 0.75 -a 20 --seed 9 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed9lr5e-2 -ps 0.75 -a 20 --seed 9 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed9lr1e-3 -ps 0.75 -a 30 --seed 9 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed9lr5e-3 -ps 0.75 -a 30 --seed 9 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed9lr1e-2 -ps 0.75 -a 30 --seed 9 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed9lr5e-2 -ps 0.75 -a 30 --seed 9 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed10lr1e-3 -ps 0.5 -a 10 --seed 10 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed10lr5e-3 -ps 0.5 -a 10 --seed 10 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed10lr1e-2 -ps 0.5 -a 10 --seed 10 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a10seed10lr5e-2 -ps 0.5 -a 10 --seed 10 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed10lr1e-3 -ps 0.5 -a 20 --seed 10 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed10lr5e-3 -ps 0.5 -a 20 --seed 10 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed10lr1e-2 -ps 0.5 -a 20 --seed 10 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a20seed10lr5e-2 -ps 0.5 -a 20 --seed 10 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed10lr1e-3 -ps 0.5 -a 30 --seed 10 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed10lr5e-3 -ps 0.5 -a 30 --seed 10 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed10lr1e-2 -ps 0.5 -a 30 --seed 10 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.5a30seed10lr5e-2 -ps 0.5 -a 30 --seed 10 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed10lr1e-3 -ps 0.75 -a 10 --seed 10 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed10lr5e-3 -ps 0.75 -a 10 --seed 10 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed10lr1e-2 -ps 0.75 -a 10 --seed 10 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a10seed10lr5e-2 -ps 0.75 -a 10 --seed 10 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed10lr1e-3 -ps 0.75 -a 20 --seed 10 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed10lr5e-3 -ps 0.75 -a 20 --seed 10 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed10lr1e-2 -ps 0.75 -a 20 --seed 10 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a20seed10lr5e-2 -ps 0.75 -a 20 --seed 10 --lr 5e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed10lr1e-3 -ps 0.75 -a 30 --seed 10 --lr 1e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed10lr5e-3 -ps 0.75 -a 30 --seed 10 --lr 5e-3
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed10lr1e-2 -ps 0.75 -a 30 --seed 10 --lr 1e-2
srun --label python evo_reinforce.py --savedir /data/lisa/exp/zac/results/evo/ps0.75a30seed10lr5e-2 -ps 0.75 -a 30 --seed 10 --lr 5e-2
source deactivate
