#!/bin/bash
## SLURM scrips have a specific format.

## job name
#SBATCH --job-name=grid_1_
#SBATCH --gres=gpu:1
#SBATCH --time=20:00:00

## %j is the job id, %u is the user id
## coment SBATCH --output=/u/kentonza/Code/snr_optimizer/pytorch/cifar10/%u/jobs/grid_1-%j.out
## filename for job standard error output (stderr)
## coment SBATCH --error=/u/kentonza/Code/snr_optimizer/pytorch/cifar10/%u/jobs/grid_1-%j.err

## number of nodes
#SBATCH --nodes=1
## number of tasks per node
#SBATCH --ntasks-per-node=1


### Section 2: Setting environment variables for the job
#FIXME
source activate py2

### Section 3:
### Jobs command
### Generated by gen.sh
